version: "3.7"

services:
  redis:
    image: redis:latest
    ports:
      - "0.0.0.0:6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      REDIS_URL: redis://:@redis:6379